apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appB.service.name }}
  labels:
    app: {{ .Values.appB.name }}
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.appB.service.grpcPort }}
    targetPort: grpc
    protocol: TCP
    name: grpc
  - port: {{ .Values.appB.service.metricsPort }}
    targetPort: metrics
    protocol: TCP
    name: metrics
  selector:
    app: {{ .Values.appB.name }}
