apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appA.service.name }}
  labels:
    app: {{ .Values.appA.name }}
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.appA.service.port }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: {{ .Values.appA.name }}
